name: Catalog Service

on:
  push:
    paths:
      - catalog-services/**
    branches:
      - '**'

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-services
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify
